#!/usr/bin/env python3
"""apex-dispatch policy compiler (python3 stdlib only).

Loads resources/dispatch.default.json, optionally merges a per-repo overlay,
validates the result against resources/schema.json plus the referential and
governance checks below, and renders the committed artifacts:

  resources/compiled/policy.json   merged default policy, sorted keys
  resources/compiled/VERSION       plugin version + sha256 of the inputs
  agents/<role>[-<effort>].md      one per enabled role (+ effort variants)
  resources/settings-snippet.json  layer A deny rules + layer I sandbox
  hooks/hooks.json                 only hook scripts present under hooks/

Artifacts are built from the default policy only; an overlay is applied at
runtime by readers (see --print-merged).

Usage: compile.py <plugin-root> [--check] [--print-merged] [--overlay PATH]
Exit: 0 ok, 1 invalid policy/overlay or stale artifacts, 2 usage.
"""
import copy
import hashlib
import json
import os
import re
import subprocess
import sys

GENERATED_MARK = "Generated by apex-dispatch scripts/compile.sh from resources/dispatch.default.json"
RESERVED_AGENT_NAMES = {"gibson-reviewer", "plan-author"}
EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
REVIEWER_DISALLOWED = ["Bash", "Edit", "Write", "MultiEdit", "NotebookEdit", "Agent", "mcp__*"]
REVIEWER_ROLES = {"reviewer", "adversarial-reviewer", "diagnoser"}
EFFORT_ORDER = ["low", "medium", "high", "xhigh"]
HOOK_TIMEOUT = 10
SUBAGENT_MATCHER = "^(apex-dispatch|apex-scope-loop):"
# Hook script -> (event, matcher) registrations, from spec section 5.1. A
# script is registered only when hooks/<script> exists; hooks are never
# toggled by policy.
HOOK_REGISTRY = [
    ("pre-agent.sh", "PreToolUse", "Agent|Task"),
    ("pre-bash.sh", "PreToolUse", "Bash"),
    ("pre-edit.sh", "PreToolUse", "Edit|Write|MultiEdit|NotebookEdit"),
    ("pre-mcp.sh", "PreToolUse", "^mcp__"),
    ("post-agent.sh", "PostToolUse", "Agent|Task"),
    ("post-agent.sh", "PostToolUseFailure", "Agent|Task"),
    ("post-bash-prune.sh", "PostToolUse", "Bash"),
    ("subagent-start.sh", "SubagentStart", SUBAGENT_MATCHER),
    ("subagent-stop.sh", "SubagentStop", SUBAGENT_MATCHER),
    ("stop-gate.sh", "Stop", None),
]


class PolicyError(Exception):
    def __init__(self, errors):
        super().__init__("\n".join(errors))
        self.errors = errors


def dumps(obj):
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def load_json(path, what):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        raise PolicyError(["%s not found: %s" % (what, path)])
    except (ValueError, OSError) as e:
        raise PolicyError(["%s is not valid JSON (%s): %s" % (what, path, e)])


# ---------------------------------------------------------------- merge ----

def _is_id_list(lst):
    return all(isinstance(x, dict) and isinstance(x.get("id"), str) for x in lst)


def deep_merge(base, over):
    """Project wins. Objects deep-merge; [] clears; lists of {id} objects merge
    by id (entries merged field by field); other lists and scalars replace."""
    if isinstance(base, dict) and isinstance(over, dict):
        out = copy.deepcopy(base)
        for k, v in over.items():
            out[k] = deep_merge(base[k], v) if k in base else copy.deepcopy(v)
        return out
    if isinstance(base, list) and isinstance(over, list):
        if not over:
            return []
        if base and _is_id_list(base) and _is_id_list(over):
            return merge_by_id(base, over)
        return copy.deepcopy(over)
    return copy.deepcopy(over)


def merge_by_id(base, over):
    out = [copy.deepcopy(b) for b in base]
    index = {e["id"]: i for i, e in enumerate(out)}
    for o in over:
        if o["id"] in index:
            out[index[o["id"]]] = deep_merge(out[index[o["id"]]], o)
        else:
            index[o["id"]] = len(out)
            out.append(copy.deepcopy(o))
    return out


def check_overlay_shape(overlay, sections, src):
    errs = []
    if not isinstance(overlay, dict):
        return ["overlay %s: top level must be a JSON object" % src]
    by_name = {s["name"]: s for s in sections}
    for key, val in overlay.items():
        if key == "$comment":
            continue
        sec = by_name.get(key)
        if sec is None:
            errs.append("overlay %s: unknown section '%s' (known: %s)" % (src, key, ", ".join(sorted(by_name))))
            continue
        if sec["kind"] == "map":
            if not isinstance(val, dict):
                errs.append("overlay %s: section '%s' must be an object" % (src, key))
            continue
        if not isinstance(val, list):
            errs.append("overlay %s: section '%s' must be a list" % (src, key))
            continue
        for i, e in enumerate(val):
            if not isinstance(e, dict) or not isinstance(e.get("id"), str) or not e["id"]:
                errs.append("overlay %s: %s[%d] must be an object with a non-empty string id" % (src, key, i))
            elif sec["merge"] == "subtract":
                r = e.get("reason")
                if not isinstance(r, str) or not r.strip():
                    errs.append("overlay %s: disabled entry '%s' has no reason (a reason is required)" % (src, e["id"]))
    return errs


def merge_policy(default, overlay, sections, src="overlay"):
    errs = check_overlay_shape(overlay, sections, src)
    if errs:
        raise PolicyError(errs)
    merged = copy.deepcopy(default)
    for sec in sections:
        name = sec["name"]
        if name not in overlay:
            continue
        over = overlay[name]
        rule = sec["merge"]
        if rule == "deep":
            merged[name] = deep_merge(merged.get(name, {}), over)
        elif rule == "by-id":
            merged[name] = [] if over == [] else merge_by_id(merged.get(name, []), over)
        elif rule == "add-only":
            if over == []:
                errs.append("overlay %s: %s cannot be cleared (hard rules outrank the overlay)" % (src, name))
                continue
            known = {e["id"] for e in merged.get(name, [])}
            for e in over:
                if e["id"] in known:
                    errs.append("overlay %s: %s '%s' already exists and cannot be replaced; add a rule with a new id" % (src, name, e["id"]))
            merged[name] = merged.get(name, []) + copy.deepcopy([e for e in over if e["id"] not in known])
        elif rule == "subtract":
            if over == []:
                merged[name] = []
            else:
                cur = merged.get(name, [])
                keyed = {(e.get("section"), e["id"]): i for i, e in enumerate(cur)}
                for e in over:
                    k = (e.get("section"), e["id"])
                    if k in keyed:
                        cur[keyed[k]] = copy.deepcopy(e)
                    else:
                        keyed[k] = len(cur)
                        cur.append(copy.deepcopy(e))
                merged[name] = cur
        else:
            errs.append("sections.json: unknown merge rule '%s' for %s" % (rule, name))
    if errs:
        raise PolicyError(errs)
    return merged


def prune_refs(value, spec, defs, removed):
    """Drop list items that reference a disabled entry (schema-driven). A
    scalar reference to a disabled entry is left for validation to reject."""
    spec = resolve(spec, defs)
    if isinstance(value, list) and "items" in spec:
        item = resolve(spec["items"], defs)
        if "ref" in item:
            value[:] = [x for x in value if (item["ref"], x) not in removed]
        else:
            for x in value:
                prune_refs(x, item, defs, removed)
    elif isinstance(value, dict):
        for k, s in list(spec.get("required", {}).items()) + list(spec.get("optional", {}).items()):
            if k in value:
                prune_refs(value[k], s, defs, removed)


def apply_disabled(policy, sections, schema):
    errs = []
    removed = set()
    targets = [s["name"] for s in sections if s["merge"] == "by-id"]
    for d in policy.get("disabled", []):
        if not isinstance(d, dict):
            continue
        did, sec = d.get("id"), d.get("section")
        if not isinstance(d.get("reason"), str) or not d["reason"].strip():
            errs.append("disabled entry '%s' has no reason (a reason is required)" % did)
            continue
        if sec is not None:
            if sec not in targets:
                hint = " (hard rules cannot be disabled)" if sec == "hard_rules" else ""
                errs.append("disabled entry '%s': section '%s' is not a by-id section%s" % (did, sec, hint))
                continue
            hits = [sec] if any(e.get("id") == did for e in policy.get(sec, [])) else []
        else:
            hits = [s for s in targets if any(e.get("id") == did for e in policy.get(s, []))]
            if any(e.get("id") == did for e in policy.get("hard_rules", [])) and not hits:
                errs.append("disabled entry '%s' names a hard rule; hard rules cannot be disabled" % did)
                continue
        if not hits:
            errs.append("disabled entry '%s' matches no entry%s" % (did, " in " + sec if sec else ""))
        elif len(hits) > 1:
            errs.append("disabled entry '%s' is ambiguous (in %s); add \"section\"" % (did, ", ".join(hits)))
        else:
            policy[hits[0]] = [e for e in policy[hits[0]] if e.get("id") != did]
            removed.add((hits[0], did))
    if errs:
        raise PolicyError(errs)
    if removed:
        prune_refs(policy, schema["root"], schema["defs"], removed)
    return policy


# ------------------------------------------------------------ validation ----

TYPE_CHECKS = {
    "string": lambda v: isinstance(v, str),
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "boolean": lambda v: isinstance(v, bool),
    "null": lambda v: v is None,
    "array": lambda v: isinstance(v, list),
    "object": lambda v: isinstance(v, dict),
}


def resolve(spec, defs):
    if "$def" in spec:
        base = dict(resolve(defs[spec["$def"]], defs))
        base.update({k: v for k, v in spec.items() if k != "$def"})
        return base
    return spec


def validate(value, spec, path, defs, errs, refs):
    spec = resolve(spec, defs)
    types = spec.get("type")
    types = [types] if isinstance(types, str) else (types or [])
    if types and not any(TYPE_CHECKS[t](value) for t in types):
        errs.append("%s: expected %s, got %s" % (path, "|".join(types), json.dumps(value)[:60]))
        return
    if "const" in spec and value != spec["const"]:
        errs.append("%s: must be %s" % (path, json.dumps(spec["const"])))
    if "enum" in spec and value not in spec["enum"]:
        errs.append("%s: %s is not one of %s" % (path, json.dumps(value), ", ".join(json.dumps(x) for x in spec["enum"])))
    if isinstance(value, str):
        if "min" in spec and len(value) < spec["min"]:
            errs.append("%s: must not be empty" % path)
        if "pattern" in spec and not re.fullmatch(spec["pattern"], value):
            errs.append("%s: %s does not match /%s/" % (path, json.dumps(value), spec["pattern"]))
        if "ref" in spec:
            refs.append((path, spec["ref"], value))
    elif isinstance(value, (int, float)) and not isinstance(value, bool):
        if "min" in spec and value < spec["min"]:
            errs.append("%s: %s is below %s" % (path, value, spec["min"]))
        if "max" in spec and value > spec["max"]:
            errs.append("%s: %s is above %s" % (path, value, spec["max"]))
    elif isinstance(value, list):
        if len(value) < spec.get("min_items", 0):
            errs.append("%s: needs at least %d item(s)" % (path, spec["min_items"]))
        if spec.get("unique"):
            seen = set()
            for x in value:
                k = json.dumps(x, sort_keys=True)
                if k in seen:
                    errs.append("%s: duplicate item %s" % (path, k))
                seen.add(k)
        if spec.get("unique_ids"):
            seen = set()
            for x in value:
                if isinstance(x, dict) and "id" in x:
                    if x["id"] in seen:
                        errs.append("%s: duplicate id %s" % (path, json.dumps(x["id"])))
                    seen.add(x["id"])
        if "items" in spec:
            for i, x in enumerate(value):
                label = x["id"] if isinstance(x, dict) and isinstance(x.get("id"), str) else i
                validate(x, spec["items"], "%s[%s]" % (path, label), defs, errs, refs)
    elif isinstance(value, dict) and ("required" in spec or "optional" in spec):
        req, opt = spec.get("required", {}), spec.get("optional", {})
        for k, s in req.items():
            if k not in value:
                errs.append("%s: missing required key '%s'" % (path, k))
            else:
                validate(value[k], s, "%s.%s" % (path, k), defs, errs, refs)
        for k, s in opt.items():
            if k in value:
                validate(value[k], s, "%s.%s" % (path, k), defs, errs, refs)
        if not spec.get("additional", False):
            for k in value:
                if k not in req and k not in opt:
                    errs.append("%s: unknown key '%s'" % (path, k))


def governance_checks(p):
    """Checks the schema language cannot express."""
    errs = []
    tiers = {t["id"]: t for t in p["tiers"]}
    ranks = [t["rank"] for t in p["tiers"]]
    if len(set(ranks)) != len(ranks):
        errs.append("tiers: ranks must be unique")
    for c in p["classes"]:
        f, ce = tiers.get(c["tier_floor"]), tiers.get(c["tier_ceiling"])
        if f and ce and f["rank"] > ce["rank"]:
            errs.append("classes[%s]: tier_floor %s is above tier_ceiling %s" % (c["id"], c["tier_floor"], c["tier_ceiling"]))
        if c["fanout"]["shape"] == "single" and c["fanout"]["max_lanes"] != 1:
            errs.append("classes[%s]: fanout single must have max_lanes 1" % c["id"])
    for r in p["roles"]:
        where = "roles[%s]" % r["id"]
        tools, dis = set(r["tools"]), set(r["disallowed_tools"])
        if r["id"] in RESERVED_AGENT_NAMES:
            errs.append("%s: name collides with an apex-scope-loop agent" % where)
        for t in r["tools"]:
            if "(" in t or "*" in t:
                errs.append("%s: tools entry %s is a pattern; tools must name whole tools (a Bash pattern grants all of Bash)" % (where, json.dumps(t)))
        if "Agent" in tools or "Task" in tools:
            errs.append("%s: no generated agent may hold Agent/Task (spawn depth 1)" % where)
        if "Agent" not in dis:
            errs.append("%s: disallowed_tools must include Agent" % where)
        if tools & dis:
            errs.append("%s: tools and disallowed_tools overlap: %s" % (where, ", ".join(sorted(tools & dis))))
        if r["read_only"] and tools & EDIT_TOOLS:
            errs.append("%s: read_only role holds edit tools %s" % (where, ", ".join(sorted(tools & EDIT_TOOLS))))
        if r["read_only"] and not EDIT_TOOLS <= dis:
            errs.append("%s: read_only role must disallow %s" % (where, ", ".join(sorted(EDIT_TOOLS))))
        if r["id"] in REVIEWER_ROLES:
            if sorted(tools) != ["Glob", "Grep", "Read"]:
                errs.append("%s: reviewer tools must be exactly Read, Grep, Glob" % where)
            if not set(REVIEWER_DISALLOWED) <= dis:
                errs.append("%s: reviewer disallowed_tools must include %s" % (where, ", ".join(REVIEWER_DISALLOWED)))
        for v in r["effort_variants"]:
            if EFFORT_ORDER.index(v) <= EFFORT_ORDER.index(r["effort"]):
                errs.append("%s: effort variant %s must be above the base effort %s" % (where, v, r["effort"]))
    for h in p["hard_rules"]:
        where = "hard_rules[%s]" % h["id"]
        need = {"route_floor": ("when", "then", "match"), "permission_deny": ("deny",), "sandbox": ("sandbox",)}[h["kind"]]
        for k in need:
            if k not in h:
                errs.append("%s: kind %s needs '%s'" % (where, h["kind"], k))
        for k in ("when", "then", "match", "deny", "sandbox"):
            if k in h and k not in need:
                errs.append("%s: kind %s does not take '%s'" % (where, h["kind"], k))
        for rule in h.get("deny", []):
            if rule.lower().startswith("ask"):
                errs.append("%s: ask rules are forbidden" % where)
    if not any(h["kind"] == "permission_deny" for h in p["hard_rules"]):
        errs.append("hard_rules: at least one permission_deny rule is required (layer A)")
    if sum(1 for h in p["hard_rules"] if h["kind"] == "sandbox") != 1:
        errs.append("hard_rules: exactly one sandbox rule is required (layer I)")
    rungs = sorted(p["escalation"]["rungs"], key=lambda r: r["at_failures"])
    if len({r["at_failures"] for r in rungs}) != len(rungs):
        errs.append("escalation.rungs: at_failures must be unique")
    if rungs and rungs[-1]["action"] != "halt":
        errs.append("escalation.rungs: the last rung must halt")
    if rungs and rungs[0]["action"] != "effort_up":
        errs.append("escalation.rungs: the first rung must raise effort before model")
    return errs


def validate_policy(policy, schema, where):
    errs, refs = [], []
    validate(policy, schema["root"], "policy", schema["defs"], errs, refs)
    if errs:
        raise PolicyError(["%s: %s" % (where, e) for e in errs])
    for path, section, value in refs:
        ids = {e.get("id") for e in policy.get(section, []) if isinstance(e, dict)}
        if value not in ids:
            errs.append("%s: unknown %s reference %s" % (path, section.rstrip("s") if section != "classes" else "class", json.dumps(value)))
    errs += governance_checks(policy) if not errs else []
    if errs:
        raise PolicyError(["%s: %s" % (where, e) for e in errs])


# ------------------------------------------------------------- rendering ----

def render_agent(role, effort, variant):
    name = role["id"] + ("-" + effort if variant else "")
    desc = role["description"]
    if variant:
        desc += " Effort %s variant, used by the escalation ladder." % effort
    for bad in (": ", " #", "\n"):
        if bad in desc:
            raise PolicyError(["roles[%s]: description must not contain %r (YAML frontmatter)" % (role["id"], bad)])
    lines = [
        "---",
        "name: " + name,
        "description: " + desc,
        "tools: " + ", ".join(role["tools"]),
        "disallowedTools: " + ", ".join(role["disallowed_tools"]),
        "effort: " + effort,
        "maxTurns: %d" % role["maxTurns"],
        "---",
        "",
        "You are the **%s** role of apex-dispatch, dispatched for one routed task. The brief from the orchestrator holds the route id, the worktree, the task, its Acceptance line, its owned paths and its budgets." % role["id"],
        "",
        "## Contract",
        "",
        role["does"],
        "",
        "## Return",
        "",
        role["returns"],
        "",
        "## Limits",
        "",
        "- Tools: %s. Not available: %s." % (", ".join(role["tools"]), ", ".join(role["disallowed_tools"])),
        "- %s" % ("Read-only: you change no files and make no commits." if role["read_only"] else "Write only inside the plan worktree and the task's owned paths; never under .dev-plan-state/, .claude/ or hooks/."),
        "- You cannot spawn other agents. If the task needs more than you can do, stop and say so in your return.",
        "- Turn limit %d. When you approach it, stop and return what you have, stating what is unfinished." % role["maxTurns"],
        "",
        GENERATED_MARK + "; edit the policy, not this file.",
        "",
    ]
    return name, "\n".join(lines)


def render_hooks(plugin_root):
    hooks_dir = os.path.join(plugin_root, "hooks")
    present = sorted(f for f in os.listdir(hooks_dir) if f.endswith(".sh")) if os.path.isdir(hooks_dir) else []
    known = {h[0] for h in HOOK_REGISTRY}
    unknown = [f for f in present if f not in known]
    if unknown:
        raise PolicyError(["hooks/: no registration for %s (add it to HOOK_REGISTRY in scripts/lib/compile.py)" % ", ".join(unknown)])
    events = {}
    for script, event, matcher in HOOK_REGISTRY:
        if script not in present:
            continue
        group = {"hooks": [{"type": "command", "command": 'bash "${CLAUDE_PLUGIN_ROOT}/hooks/%s"' % script, "timeout": HOOK_TIMEOUT}]}
        if matcher is not None:
            group["matcher"] = matcher
        events.setdefault(event, []).append(group)
    return {"hooks": events}, present


def render_settings(policy):
    deny, sandbox = [], {}
    for h in policy["hard_rules"]:
        if h["kind"] == "permission_deny":
            deny += [d for d in h["deny"] if d not in deny]
        elif h["kind"] == "sandbox":
            sandbox = copy.deepcopy(h["sandbox"])
    hosts = sorted({x for pr in policy["providers"] if pr["enabled"] for x in pr["hosts"]})
    sandbox["network"] = {"allowedDomains": hosts}
    return {"permissions": {"deny": deny}, "sandbox": sandbox}


def build(plugin_root, inputs):
    """Return {relative path: text} for every generated artifact."""
    default, sections, schema = inputs["default"], inputs["sections"], inputs["schema"]
    policy = apply_disabled(merge_policy(default, {}, sections["sections"]), sections["sections"], schema)
    validate_policy(policy, schema, "resources/dispatch.default.json")
    pj = load_json(os.path.join(plugin_root, ".claude-plugin", "plugin.json"), "plugin.json")
    hooks, hook_files = render_hooks(plugin_root)
    h = hashlib.sha256()
    for key in ("default", "sections", "schema"):
        h.update(key.encode() + b"\0" + json.dumps(inputs[key], sort_keys=True, separators=(",", ":")).encode() + b"\0")
    with open(os.path.abspath(__file__), "rb") as f:
        h.update(b"compiler\0" + f.read() + b"\0")
    h.update(b"hooks\0" + "\n".join(hook_files).encode())
    out = {
        "resources/compiled/policy.json": dumps(policy),
        "resources/compiled/VERSION": "version=%s\ninputs_sha256=%s\n" % (pj["version"], h.hexdigest()),
        "resources/settings-snippet.json": dumps(render_settings(policy)),
        "hooks/hooks.json": dumps(hooks),
    }
    for role in policy["roles"]:
        if not role["enabled"]:
            continue
        for effort, variant in [(role["effort"], False)] + [(e, True) for e in role["effort_variants"]]:
            name, text = render_agent(role, effort, variant)
            out["agents/%s.md" % name] = text
    return out


def generated_agents_on_disk(plugin_root):
    d = os.path.join(plugin_root, "agents")
    if not os.path.isdir(d):
        return []
    found = []
    for f in sorted(os.listdir(d)):
        p = os.path.join(d, f)
        if f.endswith(".md") and os.path.isfile(p):
            with open(p, encoding="utf-8") as fh:
                if GENERATED_MARK in fh.read():
                    found.append("agents/" + f)
    return found


# ------------------------------------------------------------------ main ----

def find_overlay():
    env = os.environ.get("APEX_DISPATCH_POLICY")
    if env:
        return env
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None
    p = os.path.join(top, ".claude", "apex-dispatch", "policy.json")
    return p if os.path.isfile(p) else None


def main(argv):
    if not argv:
        print("usage: compile.py <plugin-root> [--check] [--print-merged] [--overlay PATH]", file=sys.stderr)
        return 2
    root, args = os.path.abspath(argv[0]), argv[1:]
    check = printing = False
    overlay_path = None
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--check":
            check = True
        elif a == "--print-merged":
            printing = True
        elif a == "--overlay":
            if i + 1 >= len(args):
                print("compile: --overlay needs a path", file=sys.stderr)
                return 2
            overlay_path = args[i + 1]
            i += 1
        elif a in ("-h", "--help"):
            print(__doc__)
            return 0
        else:
            print("compile: unknown argument %s" % a, file=sys.stderr)
            return 2
        i += 1
    if check and printing:
        print("compile: --check and --print-merged are exclusive", file=sys.stderr)
        return 2
    res = os.path.join(root, "resources")
    try:
        inputs = {
            "default": load_json(os.path.join(res, "dispatch.default.json"), "default policy"),
            "sections": load_json(os.path.join(res, "sections.json"), "sections registry"),
            "schema": load_json(os.path.join(res, "schema.json"), "schema"),
        }
        artifacts = build(root, inputs)
        if overlay_path is None and printing:
            overlay_path = find_overlay()
        merged = None
        if overlay_path is not None:
            overlay = load_json(overlay_path, "overlay")
            secs = inputs["sections"]["sections"]
            merged = apply_disabled(merge_policy(inputs["default"], overlay, secs, overlay_path), secs, inputs["schema"])
            validate_policy(merged, inputs["schema"], "merged policy (overlay %s)" % overlay_path)
    except PolicyError as e:
        for line in e.errors:
            print("compile: " + line, file=sys.stderr)
        return 1
    if printing:
        sys.stdout.write(dumps(merged if merged is not None else json.loads(artifacts["resources/compiled/policy.json"])))
        return 0
    expected = set(artifacts)
    orphans = [a for a in generated_agents_on_disk(root) if a not in expected]
    if check:
        problems = []
        for rel in sorted(artifacts):
            p = os.path.join(root, rel)
            if not os.path.isfile(p):
                problems.append("missing: " + rel)
                continue
            with open(p, encoding="utf-8") as f:
                if f.read() != artifacts[rel]:
                    problems.append("stale: " + rel)
        problems += ["orphaned: " + a for a in orphans]
        for line in problems:
            print("compile --check: " + line, file=sys.stderr)
        if problems:
            print("compile --check: %d artifact(s) out of date; run scripts/compile.sh" % len(problems), file=sys.stderr)
            return 1
        print("compile --check: %d artifacts up to date%s" % (len(artifacts), "; overlay valid" if merged is not None else ""))
        return 0
    written = 0
    for rel, text in sorted(artifacts.items()):
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        cur = None
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                cur = f.read()
        if cur != text:
            with open(p, "w", encoding="utf-8") as f:
                f.write(text)
            written += 1
            print("compile: wrote " + rel)
    for a in orphans:
        os.remove(os.path.join(root, a))
        print("compile: removed " + a)
    print("compile: %d artifacts, %d written, %d removed%s" % (len(artifacts), written, len(orphans), "; overlay valid" if merged is not None else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
