#!/usr/bin/env python3
"""apex-dispatch policy compiler (python3 stdlib only).

Loads resources/dispatch.default.json, optionally merges a per-repo overlay,
validates the result against resources/schema.json plus the referential and
governance checks below, and renders the committed artifacts:

  resources/compiled/policy.json   merged default policy, sorted keys
  resources/compiled/VERSION       plugin version + sha256 of the inputs
  agents/<role>[-<effort>].md      one per enabled role (+ effort variants)
  resources/settings-snippet.json  layer A deny rules + layer I sandbox
  hooks/hooks.json                 only hook scripts present under hooks/

Artifacts are built from the default policy only; an overlay is applied at
runtime by readers (see --print-merged). An overlay may configure policy
within the hard rules but never weaken confinement or change what a hard rule
refers to (see overlay_checks). agents/ is fully generated: --check flags any
agents/*.md that is not an expected artifact, and comparisons are byte-exact.

Usage: compile.py <plugin-root> [--check | --write | --print-merged] [--overlay PATH]
       compile.py <plugin-root> --target codex [--out DIR] [--check | --write]
  no flag        regenerate (write) the artifacts
  --overlay PATH alone validates the overlay and checks the artifacts like
                 --check (it never rewrites the plugin); add --write to also
                 regenerate the artifacts
  --target codex the codex-side mirror of the same default policy (spec §5.1):
                 AGENTS.md (roles, their contracts and the governance rules),
                 config.toml (profiles apex-dispatch-build / -readonly with the
                 policy's sandbox and approval settings), hooks.json (a
                 PreToolUse deny hook) and apex-dispatch-deny.py (the hook: the
                 layer-A deny patterns and each provider's forbidden flags).
                 Written to --out DIR (default resources/compiled/codex/, which
                 is committed); --check compares DIR byte-exactly. Install by
                 copying the files into $CODEX_HOME or passing --out there. The
                 default (Claude) target and its --check are unchanged by it.
Exit: 0 ok, 1 invalid policy/overlay or stale artifacts, 2 usage.
"""
import copy
import hashlib
import json
import os
import re
import subprocess
import sys

GENERATED_MARK = "Generated by apex-dispatch scripts/compile.sh from resources/dispatch.default.json"
RESERVED_AGENT_NAMES = {"gibson-reviewer", "plan-author"}
EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
REVIEWER_DISALLOWED = ["Bash", "Edit", "Write", "MultiEdit", "NotebookEdit", "Agent", "mcp__*"]
REVIEWER_ROLES = {"reviewer", "adversarial-reviewer", "diagnoser"}
EFFORT_ORDER = ["low", "medium", "high", "xhigh"]
MODEL_STRENGTH = {"haiku": 0, "sonnet": 1, "opus": 2, "fable": 2}
# Layer A bypass patterns (spec 5.3 A): a provider may never be forced to pass one.
BYPASS_PREFIXES = ("--dangerously-", "--yolo", "--always-approve", "--full-auto")
BYPASS_SUBSTRINGS = ("danger-full-access",)
# Provider sandbox modes from strictest to loosest; an overlay may keep or
# tighten a default provider's mode, never loosen it.
SANDBOX_LOOSENESS = {"read-only": 0, "strict": 0, "workspace-write": 1, "danger-full-access": 2}
MAX_REVIEW_ROUNDS = 3   # spec 5.3 G: three review rounds max, in code
MAX_HALT_FAILURES = 3   # spec 5.2 step 8: failures=3 -> HALT
# Strictness orders for route_floor `then` values (higher = stricter). Matching
# hard rules combine by max: the strictest value of every matching rule wins.
SHAPE_ORDER = ["none", "solo", "six-lens", "fanout6+adversarial"]
DIVERSITY_ORDER = ["off", "warn", "block"]
FANOUT_ORDER = ["lanes", "single"]
# Roles a hard rule's review shape needs; they cannot be disabled.
SHAPE_ROLES = {"solo": ["reviewer"], "six-lens": ["reviewer"], "fanout6+adversarial": ["reviewer", "adversarial-reviewer"]}
HOOK_TIMEOUT = 10
SUBAGENT_MATCHER = "^(apex-dispatch|apex-scope-loop):"
# Hook script -> (event, matcher) registrations, from spec section 5.1. A
# script is registered only when hooks/<script> exists; hooks are never
# toggled by policy.
HOOK_REGISTRY = [
    ("pre-agent.sh", "PreToolUse", "Agent|Task"),
    ("pre-bash.sh", "PreToolUse", "Bash"),
    ("pre-edit.sh", "PreToolUse", "Edit|Write|MultiEdit|NotebookEdit"),
    ("pre-mcp.sh", "PreToolUse", "^mcp__"),
    ("post-agent.sh", "PostToolUse", "Agent|Task"),
    ("post-agent.sh", "PostToolUseFailure", "Agent|Task"),
    ("post-bash-prune.sh", "PostToolUse", "Bash"),
    ("subagent-start.sh", "SubagentStart", SUBAGENT_MATCHER),
    ("subagent-stop.sh", "SubagentStop", SUBAGENT_MATCHER),
    ("stop-gate.sh", "Stop", None),
]


class PolicyError(Exception):
    def __init__(self, errors):
        super().__init__("\n".join(errors))
        self.errors = errors


def dumps(obj):
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _no_constant(name):
    """json parse_constant hook: NaN, Infinity and -Infinity are not JSON (RFC 8259)
    and compare false against every bound, so they would slip past min/max checks."""
    raise ValueError("non-finite number %s is not allowed" % name)


def load_json(path, what):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f, parse_constant=_no_constant)
    except FileNotFoundError:
        raise PolicyError(["%s not found: %s" % (what, path)])
    except (ValueError, OSError) as e:
        raise PolicyError(["%s is not valid JSON (%s): %s" % (what, path, e)])


# ---------------------------------------------------------------- merge ----

def _is_id_list(lst):
    return all(isinstance(x, dict) and isinstance(x.get("id"), str) for x in lst)


def deep_merge(base, over):
    """Project wins. Objects deep-merge; [] clears; lists of {id} objects merge
    by id (entries merged field by field); other lists and scalars replace."""
    if isinstance(base, dict) and isinstance(over, dict):
        out = copy.deepcopy(base)
        for k, v in over.items():
            out[k] = deep_merge(base[k], v) if k in base else copy.deepcopy(v)
        return out
    if isinstance(base, list) and isinstance(over, list):
        if not over:
            return []
        if base and _is_id_list(base) and _is_id_list(over):
            return merge_by_id(base, over)
        return copy.deepcopy(over)
    return copy.deepcopy(over)


def merge_by_id(base, over):
    out = [copy.deepcopy(b) for b in base]
    index = {e["id"]: i for i, e in enumerate(out)}
    for o in over:
        if o["id"] in index:
            out[index[o["id"]]] = deep_merge(out[index[o["id"]]], o)
        else:
            index[o["id"]] = len(out)
            out.append(copy.deepcopy(o))
    return out


def check_overlay_shape(overlay, sections, src):
    errs = []
    if not isinstance(overlay, dict):
        return ["overlay %s: top level must be a JSON object" % src]
    by_name = {s["name"]: s for s in sections}
    for key, val in overlay.items():
        if key == "$comment":
            continue
        sec = by_name.get(key)
        if sec is None:
            errs.append("overlay %s: unknown section '%s' (known: %s)" % (src, key, ", ".join(sorted(by_name))))
            continue
        if sec["kind"] == "map":
            if not isinstance(val, dict):
                errs.append("overlay %s: section '%s' must be an object" % (src, key))
            continue
        if not isinstance(val, list):
            errs.append("overlay %s: section '%s' must be a list" % (src, key))
            continue
        for i, e in enumerate(val):
            if not isinstance(e, dict) or not isinstance(e.get("id"), str) or not e["id"]:
                errs.append("overlay %s: %s[%d] must be an object with a non-empty string id" % (src, key, i))
            elif sec["merge"] == "subtract":
                if "section" in e and not isinstance(e["section"], str):
                    errs.append("overlay %s: disabled entry '%s': section must be a string" % (src, e["id"]))
                r = e.get("reason")
                if not isinstance(r, str) or not r.strip():
                    errs.append("overlay %s: disabled entry '%s' has no reason (a reason is required)" % (src, e["id"]))
    return errs


def merge_policy(default, overlay, sections, src="overlay"):
    errs = check_overlay_shape(overlay, sections, src)
    if not errs and overlay:
        errs = overlay_allowlist(default, overlay, src)
    if errs:
        raise PolicyError(errs)
    merged = copy.deepcopy(default)
    for sec in sections:
        name = sec["name"]
        if name not in overlay:
            continue
        over = overlay[name]
        rule = sec["merge"]
        if rule == "deep":
            merged[name] = deep_merge(merged.get(name, {}), over)
        elif rule == "by-id":
            merged[name] = [] if over == [] else merge_by_id(merged.get(name, []), over)
            if name == "providers" and over:
                union_forbidden(default.get(name, []), over, merged[name])
        elif rule == "add-only":
            if over == []:
                errs.append("overlay %s: %s cannot be cleared (hard rules outrank the overlay)" % (src, name))
                continue
            known = {e["id"] for e in merged.get(name, [])}
            for e in over:
                if e["id"] in known:
                    errs.append("overlay %s: %s '%s' already exists and cannot be replaced; add a rule with a new id" % (src, name, e["id"]))
            merged[name] = merged.get(name, []) + copy.deepcopy([e for e in over if e["id"] not in known])
        elif rule == "subtract":
            if over == []:
                merged[name] = []
            else:
                cur = merged.get(name, [])
                keyed = {(e.get("section"), e["id"]): i for i, e in enumerate(cur)}
                for e in over:
                    k = (e.get("section"), e["id"])
                    if k in keyed:
                        cur[keyed[k]] = copy.deepcopy(e)
                    else:
                        keyed[k] = len(cur)
                        cur.append(copy.deepcopy(e))
                merged[name] = cur
        else:
            errs.append("sections.json: unknown merge rule '%s' for %s" % (rule, name))
    if errs:
        raise PolicyError(errs)
    return merged


# Provider fields an overlay may set on a default provider (an allowlist: any
# other field is refused). New provider ids come only from the default policy.
PROVIDER_OVERLAY_FIELDS = {"id", "enabled", "allowed_classes", "roles_allowed", "max_tier", "min_acceptance", "forbidden_flags",
                           "model", "verified_versions"}


def overlay_allowlist(default, overlay, src):
    """Positive checks on the raw overlay. Providers: only enabled, narrowing
    allowed_classes/roles_allowed, lowering max_tier, raising min_acceptance
    and adding forbidden_flags; no new ids; never cleared. Tiers: not
    overlayable at all (no change, no new tier, no disabling)."""
    errs = []
    if "tiers" in overlay:
        errs.append("overlay %s: tiers cannot be changed, added or cleared by an overlay (tiers are the referents of the hard floors; they come only from the default policy)" % src)
    for d in overlay.get("disabled", []):
        if d.get("section") == "tiers" or (d.get("section") is None and any(t["id"] == d.get("id") for t in default["tiers"])):
            errs.append("overlay %s: disabled entry '%s': tiers cannot be disabled by an overlay" % (src, d.get("id")))
    if "providers" not in overlay:
        return errs
    if overlay["providers"] == []:
        return errs + ["overlay %s: providers cannot be cleared by an overlay (disable a provider with enabled: false)" % src]
    dp = {e["id"]: e for e in default["providers"]}
    trank = {t["id"]: t["rank"] for t in default["tiers"]}
    for o in overlay["providers"]:
        pid = o["id"]
        where = "overlay %s: providers[%s]" % (src, pid)
        d = dp.get(pid)
        if d is None:
            errs.append("%s: an overlay may not add a provider (new providers come only from the plugin's default policy)" % where)
            continue
        for k in sorted(set(o) - PROVIDER_OVERLAY_FIELDS):
            errs.append("%s.%s: an overlay may not set this field (allowed: %s)" % (where, k, ", ".join(sorted(PROVIDER_OVERLAY_FIELDS - {"id"}))))
        if "enabled" in o and not isinstance(o["enabled"], bool):
            errs.append("%s.enabled: must be true or false" % where)
        for k in ("allowed_classes", "roles_allowed"):
            if k in o:
                if not isinstance(o[k], list) or not all(isinstance(x, str) for x in o[k]):
                    errs.append("%s.%s: must be a list of strings" % (where, k))
                elif not set(o[k]) <= set(d[k]):
                    errs.append("%s.%s: an overlay may only narrow it to a subset of the default %s" % (where, k, json.dumps(d[k])))
        if "max_tier" in o and not isinstance(o["max_tier"], str):
            errs.append("%s.max_tier: must be a tier id string" % where)
        elif "max_tier" in o and trank.get(o["max_tier"], 1 << 30) > trank[d["max_tier"]]:
            errs.append("%s.max_tier: an overlay may only lower it (default %s)" % (where, json.dumps(d["max_tier"])))
        if "min_acceptance" in o:
            v = o["min_acceptance"]
            if not isinstance(v, (int, float)) or isinstance(v, bool) or v < d["min_acceptance"]:
                errs.append("%s.min_acceptance: an overlay may only raise it (default %s)" % (where, d["min_acceptance"]))
        if "forbidden_flags" in o:
            if not isinstance(o["forbidden_flags"], list) or (o["forbidden_flags"] == [] and d["forbidden_flags"]):
                errs.append("%s.forbidden_flags: add-only; an overlay may add forbidden flags, never clear or remove them" % where)
        if "model" in o and o["model"] is not None and (not isinstance(o["model"], str) or o["model"].startswith("-")):
            errs.append("%s.model: must be a model id string (not a flag)" % where)
        if "model" in o and d["kind"] != "subprocess":
            errs.append("%s.model: only a subprocess provider's model can be set" % where)
        if "verified_versions" in o and (not isinstance(o["verified_versions"], list)
                                         or not all(isinstance(x, str) for x in o["verified_versions"])):
            errs.append("%s.verified_versions: must be a list of version strings" % where)
    return errs


def union_forbidden(base, over, merged):
    """forbidden_flags of a provider is the default's list plus the overlay's."""
    dflt = {e["id"]: e for e in base}
    out = {e["id"]: e for e in merged}
    for o in over:
        if o["id"] in dflt and isinstance(o.get("forbidden_flags"), list):
            df = dflt[o["id"]]["forbidden_flags"]
            out[o["id"]]["forbidden_flags"] = list(df) + [f for f in o["forbidden_flags"] if f not in df]


def prune_refs(value, spec, defs, removed):
    """Drop list items that reference a disabled entry (schema-driven). A
    scalar reference to a disabled entry is left for validation to reject."""
    spec = resolve(spec, defs)
    if isinstance(value, list) and "items" in spec:
        item = resolve(spec["items"], defs)
        if "ref" in item:
            value[:] = [x for x in value if (item["ref"], x) not in removed]
        else:
            for x in value:
                prune_refs(x, item, defs, removed)
    elif isinstance(value, dict):
        for k, s in list(spec.get("required", {}).items()) + list(spec.get("optional", {}).items()):
            if k in value:
                prune_refs(value[k], s, defs, removed)


def apply_disabled(policy, sections, schema):
    errs = []
    removed = set()
    targets = [s["name"] for s in sections if s["merge"] == "by-id"]
    for d in policy.get("disabled", []):
        if not isinstance(d, dict):
            continue
        did, sec = d.get("id"), d.get("section")
        if not isinstance(d.get("reason"), str) or not d["reason"].strip():
            errs.append("disabled entry '%s' has no reason (a reason is required)" % did)
            continue
        if sec is not None:
            if sec not in targets:
                hint = " (hard rules cannot be disabled)" if sec == "hard_rules" else ""
                errs.append("disabled entry '%s': section '%s' is not a by-id section%s" % (did, sec, hint))
                continue
            hits = [sec] if any(e.get("id") == did for e in policy.get(sec, [])) else []
        else:
            hits = [s for s in targets if any(e.get("id") == did for e in policy.get(s, []))]
            if any(e.get("id") == did for e in policy.get("hard_rules", [])) and not hits:
                errs.append("disabled entry '%s' names a hard rule; hard rules cannot be disabled" % did)
                continue
        if not hits:
            errs.append("disabled entry '%s' matches no entry%s" % (did, " in " + sec if sec else ""))
        elif len(hits) > 1:
            errs.append("disabled entry '%s' is ambiguous (in %s); add \"section\"" % (did, ", ".join(hits)))
        else:
            policy[hits[0]] = [e for e in policy[hits[0]] if e.get("id") != did]
            removed.add((hits[0], did))
    if errs:
        raise PolicyError(errs)
    if removed:
        prune_refs(policy, schema["root"], schema["defs"], removed)
    return policy


# ------------------------------------------------------------ validation ----

TYPE_CHECKS = {
    "string": lambda v: isinstance(v, str),
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "boolean": lambda v: isinstance(v, bool),
    "null": lambda v: v is None,
    "array": lambda v: isinstance(v, list),
    "object": lambda v: isinstance(v, dict),
}


def resolve(spec, defs):
    if "$def" in spec:
        base = dict(resolve(defs[spec["$def"]], defs))
        base.update({k: v for k, v in spec.items() if k != "$def"})
        return base
    return spec


def validate(value, spec, path, defs, errs, refs):
    spec = resolve(spec, defs)
    types = spec.get("type")
    types = [types] if isinstance(types, str) else (types or [])
    if types and not any(TYPE_CHECKS[t](value) for t in types):
        errs.append("%s: expected %s, got %s" % (path, "|".join(types), json.dumps(value)[:60]))
        return
    if "const" in spec and value != spec["const"]:
        errs.append("%s: must be %s" % (path, json.dumps(spec["const"])))
    if "enum" in spec and value not in spec["enum"]:
        errs.append("%s: %s is not one of %s" % (path, json.dumps(value), ", ".join(json.dumps(x) for x in spec["enum"])))
    if isinstance(value, str):
        if "min" in spec and len(value) < spec["min"]:
            errs.append("%s: must not be empty" % path)
        if "pattern" in spec and not re.fullmatch(spec["pattern"], value):
            errs.append("%s: %s does not match /%s/" % (path, json.dumps(value), spec["pattern"]))
        if "ref" in spec:
            refs.append((path, spec["ref"], value))
    elif isinstance(value, (int, float)) and not isinstance(value, bool):
        if "min" in spec and value < spec["min"]:
            errs.append("%s: %s is below %s" % (path, value, spec["min"]))
        if "max" in spec and value > spec["max"]:
            errs.append("%s: %s is above %s" % (path, value, spec["max"]))
    elif isinstance(value, list):
        if len(value) < spec.get("min_items", 0):
            errs.append("%s: needs at least %d item(s)" % (path, spec["min_items"]))
        if spec.get("unique"):
            seen = set()
            for x in value:
                k = json.dumps(x, sort_keys=True)
                if k in seen:
                    errs.append("%s: duplicate item %s" % (path, k))
                seen.add(k)
        if spec.get("unique_ids"):
            seen = set()
            for x in value:
                if isinstance(x, dict) and "id" in x:
                    if x["id"] in seen:
                        errs.append("%s: duplicate id %s" % (path, json.dumps(x["id"])))
                    seen.add(x["id"])
        if "items" in spec:
            for i, x in enumerate(value):
                label = x["id"] if isinstance(x, dict) and isinstance(x.get("id"), str) else i
                validate(x, spec["items"], "%s[%s]" % (path, label), defs, errs, refs)
    elif isinstance(value, dict) and ("required" in spec or "optional" in spec):
        req, opt = spec.get("required", {}), spec.get("optional", {})
        for k, s in req.items():
            if k not in value:
                errs.append("%s: missing required key '%s'" % (path, k))
            else:
                validate(value[k], s, "%s.%s" % (path, k), defs, errs, refs)
        for k, s in opt.items():
            if k in value:
                validate(value[k], s, "%s.%s" % (path, k), defs, errs, refs)
        if not spec.get("additional", False):
            for k in value:
                if k not in req and k not in opt:
                    errs.append("%s: unknown key '%s'" % (path, k))


def governance_checks(p):
    """Checks the schema language cannot express."""
    errs = []
    tiers = {t["id"]: t for t in p["tiers"]}
    ranks = [t["rank"] for t in p["tiers"]]
    if len(set(ranks)) != len(ranks):
        errs.append("tiers: ranks must be unique")
    for c in p["classes"]:
        f, ce = tiers.get(c["tier_floor"]), tiers.get(c["tier_ceiling"])
        if f and ce and f["rank"] > ce["rank"]:
            errs.append("classes[%s]: tier_floor %s is above tier_ceiling %s" % (c["id"], c["tier_floor"], c["tier_ceiling"]))
        if c["fanout"]["shape"] == "single" and c["fanout"]["max_lanes"] != 1:
            errs.append("classes[%s]: fanout single must have max_lanes 1" % c["id"])
    for r in p["roles"]:
        where = "roles[%s]" % r["id"]
        tools, dis = set(r["tools"]), set(r["disallowed_tools"])
        if r["id"] in RESERVED_AGENT_NAMES:
            errs.append("%s: name collides with an apex-scope-loop agent" % where)
        for t in r["tools"]:
            if "(" in t or "*" in t:
                errs.append("%s: tools entry %s is a pattern; tools must name whole tools (a Bash pattern grants all of Bash)" % (where, json.dumps(t)))
        if "Agent" in tools or "Task" in tools:
            errs.append("%s: no generated agent may hold Agent/Task (spawn depth 1)" % where)
        if "Agent" not in dis:
            errs.append("%s: disallowed_tools must include Agent" % where)
        if tools & dis:
            errs.append("%s: tools and disallowed_tools overlap: %s" % (where, ", ".join(sorted(tools & dis))))
        if r["read_only"] and tools & EDIT_TOOLS:
            errs.append("%s: read_only role holds edit tools %s" % (where, ", ".join(sorted(tools & EDIT_TOOLS))))
        if r["read_only"] and not EDIT_TOOLS <= dis:
            errs.append("%s: read_only role must disallow %s" % (where, ", ".join(sorted(EDIT_TOOLS))))
        if r["id"] in REVIEWER_ROLES:
            if sorted(tools) != ["Glob", "Grep", "Read"]:
                errs.append("%s: reviewer tools must be exactly Read, Grep, Glob" % where)
            if not set(REVIEWER_DISALLOWED) <= dis:
                errs.append("%s: reviewer disallowed_tools must include %s" % (where, ", ".join(REVIEWER_DISALLOWED)))
        for v in r["effort_variants"]:
            if EFFORT_ORDER.index(v) <= EFFORT_ORDER.index(r["effort"]):
                errs.append("%s: effort variant %s must be above the base effort %s" % (where, v, r["effort"]))
    for h in p["hard_rules"]:
        where = "hard_rules[%s]" % h["id"]
        need = {"route_floor": ("when", "then", "match"), "permission_deny": ("deny",), "sandbox": ("sandbox",)}[h["kind"]]
        for k in need:
            if k not in h:
                errs.append("%s: kind %s needs '%s'" % (where, h["kind"], k))
        for k in ("when", "then", "match", "deny", "sandbox"):
            if k in h and k not in need:
                errs.append("%s: kind %s does not take '%s'" % (where, h["kind"], k))
        for rule in h.get("deny", []):
            if rule.lower().startswith("ask"):
                errs.append("%s: ask rules are forbidden" % where)
    if not any(h["kind"] == "permission_deny" for h in p["hard_rules"]):
        errs.append("hard_rules: at least one permission_deny rule is required (layer A)")
    if sum(1 for h in p["hard_rules"] if h["kind"] == "sandbox") != 1:
        errs.append("hard_rules: exactly one sandbox rule is required (layer I)")
    rungs = sorted(p["escalation"]["rungs"], key=lambda r: r["at_failures"])
    if len({r["at_failures"] for r in rungs}) != len(rungs):
        errs.append("escalation.rungs: at_failures must be unique")
    if rungs and rungs[-1]["action"] != "halt":
        errs.append("escalation.rungs: the last rung must halt")
    if rungs and rungs[0]["action"] != "effort_up":
        errs.append("escalation.rungs: the first rung must raise effort before model")
    if p["escalation"]["max_review_rounds"] > MAX_REVIEW_ROUNDS:
        errs.append("escalation.max_review_rounds: %d is above %d (three review rounds max)" % (p["escalation"]["max_review_rounds"], MAX_REVIEW_ROUNDS))
    if rungs and rungs[-1]["at_failures"] > MAX_HALT_FAILURES:
        errs.append("escalation.rungs: the halt rung at_failures %d is above %d (failures=3 halts)" % (rungs[-1]["at_failures"], MAX_HALT_FAILURES))
    # Tier ranks are monotonic with model strength and effort.
    by_rank = sorted(p["tiers"], key=lambda t: t["rank"])
    for lo, hi in zip(by_rank, by_rank[1:]):
        if MODEL_STRENGTH[lo["model"]] > MODEL_STRENGTH[hi["model"]]:
            errs.append("tiers: tier %s (rank %d, %s) is above tier %s (rank %d, %s) but uses a weaker model; rank must be monotonic with model strength" % (hi["id"], hi["rank"], hi["model"], lo["id"], lo["rank"], lo["model"]))
        if EFFORT_ORDER.index(lo["effort"]) > EFFORT_ORDER.index(hi["effort"]):
            errs.append("tiers: tier %s (rank %d, effort %s) is above tier %s (rank %d, effort %s) but uses a lower effort; rank must be monotonic with effort" % (hi["id"], hi["rank"], hi["effort"], lo["id"], lo["rank"], lo["effort"]))
    # Provider confinement: no forced flag may bypass layer A or a forbidden flag.
    for pr in p["providers"]:
        where = "providers[%s]" % pr["id"]
        forbidden = set(pr["forbidden_flags"])
        for f in pr["forced_flags"]:
            if f.startswith(BYPASS_PREFIXES) or any(x in f for x in BYPASS_SUBSTRINGS):
                errs.append("%s: forced flag %s matches a layer-A bypass pattern" % (where, json.dumps(f)))
            elif f in forbidden or f.split("=", 1)[0] in forbidden:
                errs.append("%s: forced flag %s is in forbidden_flags" % (where, json.dumps(f)))
        if pr["sandbox_mode"] is not None and any(x in pr["sandbox_mode"] for x in BYPASS_SUBSTRINGS):
            errs.append("%s: sandbox_mode %s disables provider confinement" % (where, json.dumps(pr["sandbox_mode"])))
    # Roles a hard rule's review shape needs cannot be disabled.
    enabled = {r["id"] for r in p["roles"] if r["enabled"]}
    for h in p["hard_rules"]:
        shape = h.get("then", {}).get("review_shape")
        for role in SHAPE_ROLES.get(shape, []):
            if role not in enabled:
                errs.append("roles[%s]: required by hard rule %s (review_shape %s) and cannot be disabled" % (role, h["id"], shape))
    return errs


def _rank(order, v):
    return order.index(v) if v in order else -1


def _when_overlaps(a, b):
    """True when two route_floor `when` objects share a condition (equal value,
    or intersecting tags_any); identical conditions always overlap."""
    if a == b:
        return True
    for k in set(a) & set(b):
        if k == "tags_any":
            if set(a[k]) & set(b[k]):
                return True
        elif a[k] == b[k]:
            return True
    return False


def _weaker_then(new, old, tiers):
    """Names of `then` keys where `new` is weaker than `old` (route_floor rules
    combine by max, so an appended rule may only match or tighten)."""
    rank = {t["id"]: t["rank"] for t in tiers}
    weak = []
    for k in set(new) & set(old):
        n, o = new[k], old[k]
        if k == "review_shape":
            bad = _rank(SHAPE_ORDER, n) < _rank(SHAPE_ORDER, o)
        elif k == "review_diversity":
            bad = _rank(DIVERSITY_ORDER, n) < _rank(DIVERSITY_ORDER, o)
        elif k == "fanout":
            bad = _rank(FANOUT_ORDER, n) < _rank(FANOUT_ORDER, o)
        elif k == "tier_floor":
            bad = rank.get(n, -1) < rank.get(o, -1)
        elif k == "tier_ceiling":
            bad = rank.get(n, 1 << 30) > rank.get(o, 1 << 30)
        elif k == "tier_floor_rungs_above_last":
            bad = n < o
        elif k == "classes_only":
            bad = not set(n) <= set(o)
        else:  # class, reviewer_family, external_builders, human_gate: must match
            bad = n != o
        if bad:
            weak.append(k)
    return sorted(weak)


def overlay_checks(default, merged):
    """An overlay may configure policy within the hard rules but never weaken
    confinement or change what a hard rule refers to. `default` is the
    validated default policy; `merged` the validated overlay-merged policy."""
    errs = []
    dmap = lambda sec: {e["id"]: e for e in default[sec]}
    # Tiers: the referents of the hard floors (strong = opus/high, ...).
    dt = dmap("tiers")
    for t in merged["tiers"]:
        d = dt.get(t["id"])
        for k in ("model", "effort", "rank") if d else ():
            if t[k] != d[k]:
                errs.append("tiers[%s].%s: an overlay may not change %s (default %s); a hard rule refers to it" % (t["id"], k, json.dumps(t[k]), json.dumps(d[k])))
    # Providers: identity and confinement.
    dp = dmap("providers")
    for pr in merged["providers"]:
        d = dp.get(pr["id"])
        if not d:
            continue
        where = "providers[%s]" % pr["id"]
        for k in ("kind", "family", "binary"):
            if pr[k] != d[k]:
                errs.append("%s.%s: an overlay may not change %s (default %s)" % (where, k, json.dumps(pr[k]), json.dumps(d[k])))
        missing = [f for f in d["forbidden_flags"] if f not in pr["forbidden_flags"]]
        if missing:
            errs.append("%s.forbidden_flags: an overlay may not remove %s (add-only)" % (where, ", ".join(missing)))
        if pr["forced_flags"][:len(d["forced_flags"])] != d["forced_flags"]:
            errs.append("%s.forced_flags: an overlay may not remove or replace the default forced flags (append only)" % where)
        if pr["sandbox_mode"] != d["sandbox_mode"]:
            old, new = d["sandbox_mode"], pr["sandbox_mode"]
            if old is None or new is None or old not in SANDBOX_LOOSENESS or new not in SANDBOX_LOOSENESS \
                    or SANDBOX_LOOSENESS[new] > SANDBOX_LOOSENESS[old]:
                errs.append("%s.sandbox_mode: an overlay may not loosen or remove the sandbox mode (%s -> %s; order read-only|strict < workspace-write < danger-full-access)" % (where, json.dumps(old), json.dumps(new)))
    # Roles: read-only stays read-only; tools only shrink; disallowed only grow.
    dr = dmap("roles")
    for r in merged["roles"]:
        d = dr.get(r["id"])
        if not d:
            continue
        where = "roles[%s]" % r["id"]
        if d["read_only"] and not r["read_only"]:
            errs.append("%s.read_only: an overlay may not make a read-only role writable" % where)
        added = [t for t in r["tools"] if t not in d["tools"]]
        if added:
            errs.append("%s.tools: an overlay may not grant %s (tools may only be removed)" % (where, ", ".join(added)))
        dropped = [t for t in d["disallowed_tools"] if t not in r["disallowed_tools"]]
        if dropped:
            errs.append("%s.disallowed_tools: an overlay may not remove %s (add-only)" % (where, ", ".join(dropped)))
    # Appended route_floor rules may not be weaker than a default rule they overlap.
    dh = [h for h in default["hard_rules"] if h["kind"] == "route_floor"]
    known = {h["id"] for h in default["hard_rules"]}
    for h in merged["hard_rules"]:
        if h["id"] in known or h["kind"] != "route_floor":
            continue
        if "tier_ceiling" in h["then"]:
            errs.append("hard_rules[%s].then.tier_ceiling: an overlay-appended rule may not set a tier ceiling (it could undercut a default rule's tier floor)" % h["id"])
        for d in dh:
            if _when_overlaps(h["when"], d["when"]):
                weak = _weaker_then(h["then"], d["then"], merged["tiers"])
                if weak:
                    errs.append("hard_rules[%s]: weaker than hard rule %s on an overlapping condition (%s); matching hard rules combine by max, so an added rule may only match or tighten" % (h["id"], d["id"], ", ".join(weak)))
    # Escalation: stricter, never looser.
    me, de = merged["escalation"], default["escalation"]
    if me["max_review_rounds"] > de["max_review_rounds"]:
        errs.append("escalation.max_review_rounds: an overlay may lower it, not raise it above %d" % de["max_review_rounds"])
    halt = lambda e: max((r["at_failures"] for r in e["rungs"] if r["action"] == "halt"), default=0)
    if halt(me) > halt(de):
        errs.append("escalation.rungs: an overlay may not move the halt rung above at_failures %d" % halt(de))
    return errs


def validate_policy(policy, schema, where, extra=None):
    """Schema, references, then governance (plus `extra`, e.g. overlay_checks)
    on a schema-valid policy; every problem is reported together."""
    errs, refs = [], []
    validate(policy, schema["root"], "policy", schema["defs"], errs, refs)
    if errs:
        raise PolicyError(["%s: %s" % (where, e) for e in errs])
    for path, section, value in refs:
        ids = {e.get("id") for e in policy.get(section, []) if isinstance(e, dict)}
        if value not in ids:
            errs.append("%s: unknown %s reference %s" % (path, section.rstrip("s") if section != "classes" else "class", json.dumps(value)))
    if not errs:
        errs += governance_checks(policy)
        errs += extra(policy) if extra else []
    if errs:
        raise PolicyError(["%s: %s" % (where, e) for e in errs])


# ------------------------------------------------------------- rendering ----

def render_agent(role, effort, variant):
    name = role["id"] + ("-" + effort if variant else "")
    desc = role["description"]
    if variant:
        desc += " Effort %s variant, used by the escalation ladder." % effort
    for bad in (": ", " #", "\n"):
        if bad in desc:
            raise PolicyError(["roles[%s]: description must not contain %r (YAML frontmatter)" % (role["id"], bad)])
    lines = [
        "---",
        "name: " + name,
        "description: " + desc,
        "tools: " + ", ".join(role["tools"]),
        "disallowedTools: " + ", ".join(role["disallowed_tools"]),
        "effort: " + effort,
        "maxTurns: %d" % role["maxTurns"],
        "---",
        "",
        "You are the **%s** role of apex-dispatch, dispatched for one routed task. The brief from the orchestrator holds the route id, the worktree, the task, its Acceptance line, its owned paths and its budgets." % role["id"],
        "",
        "## Contract",
        "",
        role["does"],
        "",
        "## Return",
        "",
        role["returns"],
        "",
        "## Limits",
        "",
        "- Tools: %s. Not available: %s." % (", ".join(role["tools"]), ", ".join(role["disallowed_tools"])),
        "- %s" % ("Read-only: you change no files and make no commits." if role["read_only"] else "Write only inside the plan worktree and the task's owned paths; never under .dev-plan-state/, .claude/ or hooks/."),
        "- You cannot spawn other agents. If the task needs more than you can do, stop and say so in your return.",
        "- Turn limit %d. When you approach it, stop and return what you have, stating what is unfinished." % role["maxTurns"],
        "",
        GENERATED_MARK + "; edit the policy, not this file.",
        "",
    ]
    return name, "\n".join(lines)


def render_hooks(plugin_root):
    hooks_dir = os.path.join(plugin_root, "hooks")
    present = sorted(f for f in os.listdir(hooks_dir) if f.endswith(".sh")) if os.path.isdir(hooks_dir) else []
    known = {h[0] for h in HOOK_REGISTRY}
    unknown = [f for f in present if f not in known]
    if unknown:
        raise PolicyError(["hooks/: no registration for %s (add it to HOOK_REGISTRY in scripts/lib/compile.py)" % ", ".join(unknown)])
    events = {}
    for script, event, matcher in HOOK_REGISTRY:
        if script not in present:
            continue
        group = {"hooks": [{"type": "command", "command": 'bash "${CLAUDE_PLUGIN_ROOT}/hooks/%s"' % script, "timeout": HOOK_TIMEOUT}]}
        if matcher is not None:
            group["matcher"] = matcher
        events.setdefault(event, []).append(group)
    return {"hooks": events}, present


def render_settings(policy):
    deny, sandbox = [], {}
    for h in policy["hard_rules"]:
        if h["kind"] == "permission_deny":
            deny += [d for d in h["deny"] if d not in deny]
        elif h["kind"] == "sandbox":
            sandbox = copy.deepcopy(h["sandbox"])
    hosts = sorted({x for pr in policy["providers"] if pr["enabled"] for x in pr["hosts"]})
    sandbox["network"] = {"allowedDomains": hosts}
    return {"permissions": {"deny": deny}, "sandbox": sandbox}


def build(plugin_root, inputs):
    """Return {relative path: text} for every generated artifact."""
    default, sections, schema = inputs["default"], inputs["sections"], inputs["schema"]
    policy = apply_disabled(merge_policy(default, {}, sections["sections"]), sections["sections"], schema)
    validate_policy(policy, schema, "resources/dispatch.default.json")
    pj = load_json(os.path.join(plugin_root, ".claude-plugin", "plugin.json"), "plugin.json")
    hooks, hook_files = render_hooks(plugin_root)
    h = hashlib.sha256()
    for key in ("default", "sections", "schema"):
        h.update(key.encode() + b"\0" + json.dumps(inputs[key], sort_keys=True, separators=(",", ":")).encode() + b"\0")
    with open(os.path.abspath(__file__), "rb") as f:
        h.update(b"compiler\0" + f.read() + b"\0")
    h.update(b"hooks\0" + "\n".join(hook_files).encode())
    out = {
        "resources/compiled/policy.json": dumps(policy),
        "resources/compiled/VERSION": "version=%s\ninputs_sha256=%s\n" % (pj["version"], h.hexdigest()),
        "resources/settings-snippet.json": dumps(render_settings(policy)),
        "hooks/hooks.json": dumps(hooks),
    }
    for role in policy["roles"]:
        if not role["enabled"]:
            continue
        for effort, variant in [(role["effort"], False)] + [(e, True) for e in role["effort_variants"]]:
            name, text = render_agent(role, effort, variant)
            out["agents/%s.md" % name] = text
    return out


# ------------------------------------------------------- codex target ----

CODEX_MARK = "Generated by apex-dispatch scripts/compile.sh --target codex from resources/dispatch.default.json"
CODEX_DENY_SCRIPT = "apex-dispatch-deny.py"


def _codex_settings(policy):
    """(sandbox_mode, approval_policy) of the codex provider's forced flags."""
    cx = next((p for p in policy["providers"] if p["id"] == "codex"), None) or {}
    ff = cx.get("forced_flags") or []
    sandbox = cx.get("sandbox_mode") or "read-only"
    for i, f in enumerate(ff[:-1]):
        if f in ("--sandbox", "-s"):
            sandbox = ff[i + 1]
    approval = "never"
    for i, f in enumerate(ff[:-1]):
        if f == "-c" and ff[i + 1].startswith("approval_policy="):
            approval = ff[i + 1].split("=", 1)[1]
    return sandbox, approval


def _deny_rules(policy):
    globs = []
    for h in policy["hard_rules"]:
        if h["kind"] == "permission_deny":
            for d in h["deny"]:
                m = re.fullmatch(r"Bash\((.*)\)", d)
                if m and m.group(1) not in globs:
                    globs.append(m.group(1))
    flags = {}
    for p in policy["providers"]:
        if p.get("binary") and p["forbidden_flags"]:
            flags.setdefault(p["binary"], [])
            flags[p["binary"]] += [f for f in p["forbidden_flags"] if f not in flags[p["binary"]]]
    return {"deny_globs": globs, "bypass_prefixes": list(BYPASS_PREFIXES), "bypass_substrings": list(BYPASS_SUBSTRINGS),
            "provider_forbidden_flags": flags}


CODEX_DENY_BODY = r'''
import fnmatch, json, os, re, shlex, sys

MAX_DEPTH = 4
WRAPPERS = {"env", "timeout", "sudo", "nice", "nohup", "stdbuf", "command", "exec", "time", "ionice", "doas"}
VALUED = {"sudo": {"-u", "-g", "-C", "-D", "-h", "-p", "-r", "-t", "-U"}, "timeout": {"-s", "--signal", "-k", "--kill-after"},
          "nice": {"-n"}, "ionice": {"-c", "-n"}, "env": {"-u", "--unset", "-C", "--chdir", "-S"},
          "stdbuf": {"-i", "-o", "-e"}, "doas": {"-u"}}
RUNNERS = {"npx", "bunx", "pnpx", "uvx"}
PACKAGES = {"opencode-ai": "opencode", "@openai/codex": "codex", "@anthropic-ai/claude-code": "claude",
            "aider-chat": "aider", "@vibe-kit/grok-cli": "grok"}
SHELLS = {"bash", "sh", "zsh", "dash", "ksh"}
ASSIGN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")


def split_segments(cmd):
    """Simple commands of a shell string: split on ; & && || | and newlines."""
    try:
        lex = shlex.shlex(cmd.replace("\n", " ; "), posix=True, punctuation_chars=";&|")
        lex.whitespace_split = True
        toks = list(lex)
    except ValueError:
        toks = cmd.replace("\n", " ; ").split()
    segs, seg = [], []
    for t in toks:
        if t and set(t) <= set(";&|"):
            if seg:
                segs.append(seg)
            seg = []
        else:
            seg.append(t)
    if seg:
        segs.append(seg)
    return segs


def package_bin(pkg):
    pkg = re.sub(r"(?<=.)@[^/@]*$", "", pkg)          # drop a version: opencode-ai@1.2 -> opencode-ai
    return PACKAGES.get(pkg, pkg.rsplit("/", 1)[-1])


def unwrap(words):
    """Strip env assignments, wrappers (env, timeout N, sudo, nice, nohup, stdbuf,
    command, exec, time) and package runners (npx/bunx/pnpx/uvx X, pnpm|yarn dlx X,
    pipx run X); returns the words of the command that actually runs."""
    w = list(words)
    while w:
        b = os.path.basename(w[0])
        if ASSIGN.match(w[0]):
            w = w[1:]
            continue
        if b in WRAPPERS:
            w = w[1:]
            while w and (w[0].startswith("-") or (b == "env" and ASSIGN.match(w[0]))):
                w = w[2:] if w[0] in VALUED.get(b, ()) else w[1:]
            if b == "timeout" and w:
                w = w[1:]                                 # the duration
            continue
        if b in RUNNERS or (b in ("pnpm", "yarn") and w[1:2] == ["dlx"]) or (b == "pipx" and w[1:2] == ["run"]):
            w = w[2:] if b in ("pnpm", "yarn", "pipx") else w[1:]
            while w and w[0].startswith("-"):
                w = w[2:] if w[0] in ("-p", "--package", "--from") else w[1:]
            if w:
                w = [package_bin(w[0])] + w[1:]
            return w
        break
    return w


def reason_words(words, depth):
    if depth > MAX_DEPTH or not words:
        return None
    for x in words:
        if x.startswith(tuple(RULES["bypass_prefixes"])) or any(s in x for s in RULES["bypass_substrings"]):
            return "bypass flag %s is forbidden" % x
    w = unwrap(words)
    if not w:
        return None
    line = " ".join(w)
    for g in RULES["deny_globs"]:
        if fnmatch.fnmatchcase(line, g):
            return "matches the deny rule Bash(%s)" % g
    base = os.path.basename(w[0])
    if base in SHELLS:
        for k, x in enumerate(w[1:], 1):
            if re.fullmatch(r"-[a-zA-Z]*c[a-zA-Z]*", x) and k + 1 < len(w):
                return reason_cmd(w[k + 1], depth + 1)
    for f in RULES["provider_forbidden_flags"].get(base, []):
        if any(a == f or a.startswith(f + "=") for a in w[1:]):
            return "flag %s is forbidden for %s" % (f, base)
    return None


def reason_cmd(cmd, depth=0):
    if depth > MAX_DEPTH:
        return None
    for g in RULES["deny_globs"]:
        if fnmatch.fnmatchcase(cmd, g):
            return "matches the deny rule Bash(%s)" % g
    for seg in split_segments(cmd):
        why = reason_words(seg, depth)
        if why:
            return why
    return None


def reason(cmd):
    if isinstance(cmd, list):                           # an argv list: one command, no shell parsing
        return reason_words([str(x) for x in cmd], 0)
    return reason_cmd(cmd)


def main():
    try:
        p = json.load(sys.stdin)
    except ValueError:
        return 0
    ti = p.get("tool_input") if isinstance(p, dict) else None
    cmd = ti.get("command") if isinstance(ti, dict) else None
    if not isinstance(cmd, (str, list)):
        return 0
    why = reason(cmd)
    if why:
        print("apex-dispatch: " + why, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def render_codex(policy, version):
    """{file name: text} for the codex target (spec §5.1 `--target codex`)."""
    sandbox, approval = _codex_settings(policy)
    rules = _deny_rules(policy)
    roles = [r for r in policy["roles"] if r["enabled"]]
    md = ["# apex-dispatch roles and rules for Codex", "",
          "<!-- %s; edit the policy, not this file. apex-dispatch %s. -->" % (CODEX_MARK, version), "",
          "These are the roles and governance rules apex-dispatch applies to Claude Code subagents, mirrored for a "
          "Codex session. A routed brief names your role; follow that role's contract exactly.", "",
          "## Rules that always hold", "",
          "- Never pass a bypass flag (anything starting with %s, or containing %s)."
          % (", ".join("`%s`" % x for x in rules["bypass_prefixes"]), ", ".join("`%s`" % x for x in rules["bypass_substrings"])),
          "- Commands matching these patterns are denied: %s." % ", ".join("`%s`" % g for g in rules["deny_globs"]),
          "- Never write under `.dev-plan-state/`, `.claude/apex-dispatch/`, `.claude/settings*.json`, `.claude/hooks/`, "
          "`hooks/hooks.json`, `.mcp.json`, `.env*`, `.envrc` or key files; stay inside the task's owned Paths.",
          "- Do not commit or push: the orchestrator applies your patch (`scripts/apply.sh`).",
          "- A review ends with one final line that is exactly `VERDICT: APPROVE` or `VERDICT: REQUEST_CHANGES`; "
          "mark blocking findings `[blocking]`.", "",
          "## Forbidden flags per provider CLI", ""]
    for b, fl in sorted(rules["provider_forbidden_flags"].items()):
        md.append("- `%s`: %s" % (b, ", ".join("`%s`" % f for f in fl)))
    md += ["", "## Roles", ""]
    for r in roles:
        md += ["### %s" % r["id"], "", r["description"], "",
               "- Contract: " + r["does"],
               "- Return: " + r["returns"],
               "- Tools: %s. Not available: %s." % (", ".join(r["tools"]), ", ".join(r["disallowed_tools"])),
               "- %s" % ("Read-only: change no files and make no commits." if r["read_only"] else
                         "Write only inside the task's owned Paths."),
               "- Turn limit %d." % r["maxTurns"], ""]
    toml = ["# %s; edit the policy, not this file." % CODEX_MARK,
            "# apex-dispatch %s. Install: copy into $CODEX_HOME (default ~/.codex) or run" % version,
            "#   scripts/compile.sh --target codex --out \"$CODEX_HOME\"",
            "# bin/worker-codex.sh never reads it (it passes --ignore-user-config and forces the same settings);",
            "# these profiles run codex by hand under the same rules: codex --profile apex-dispatch-build.",
            "",
            "[profiles.apex-dispatch-build]",
            "approval_policy = \"%s\"" % approval,
            "sandbox_mode = \"%s\"" % sandbox,
            "",
            "[profiles.apex-dispatch-readonly]",
            "approval_policy = \"%s\"" % approval,
            "sandbox_mode = \"read-only\"",
            ""]
    hooks_json = {"$comment": "%s; install beside %s in $CODEX_HOME." % (CODEX_MARK, CODEX_DENY_SCRIPT),
                  "hooks": {"PreToolUse": [{"matcher": "Bash|shell|exec_command|local_shell",
                                            "hooks": [{"type": "command", "timeout": HOOK_TIMEOUT,
                                                       "command": 'python3 "${CODEX_HOME:-$HOME/.codex}/%s"' % CODEX_DENY_SCRIPT}]}]}}
    script = ("#!/usr/bin/env python3\n# %s; edit the policy, not this file.\n"
              "# A PreToolUse command hook: reads the tool call JSON on stdin (command as a string or an argv\n"
              "# list); each simple command (split on ; & && || | and newlines, wrappers and package runners\n"
              "# stripped, bash/sh/zsh -c scripts unwrapped) is checked; exit 2 with the reason on stderr\n"
              "# denies, exit 0 allows. String matching, not a sandbox.\n"
              "RULES = %s\n" % (CODEX_MARK, json.dumps(rules, indent=1, sort_keys=True))) + CODEX_DENY_BODY
    return {"AGENTS.md": "\n".join(md), "config.toml": "\n".join(toml), "hooks.json": dumps(hooks_json),
            CODEX_DENY_SCRIPT: script}


def codex_target(root, inputs, out_dir, check):
    artifacts = build(root, inputs)                 # validates the default policy
    policy = json.loads(artifacts["resources/compiled/policy.json"])
    pj = load_json(os.path.join(root, ".claude-plugin", "plugin.json"), "plugin.json")
    files = render_codex(policy, pj["version"])
    out_dir = out_dir or os.path.join(root, "resources", "compiled", "codex")
    if check:
        problems = []
        for name in sorted(files):
            p = os.path.join(out_dir, name)
            if not os.path.isfile(p):
                problems.append("missing: " + p)
            elif read_text(p) != files[name]:
                problems.append("stale: " + p)
        for line in problems:
            print("compile --target codex --check: " + line, file=sys.stderr)
        if problems:
            print("compile --target codex --check: %d artifact(s) out of date; run scripts/compile.sh --target codex%s"
                  % (len(problems), "" if out_dir == os.path.join(root, "resources", "compiled", "codex") else " --out " + out_dir),
                  file=sys.stderr)
            return 1
        print("compile --target codex --check: %d artifacts up to date in %s" % (len(files), out_dir))
        return 0
    os.makedirs(out_dir, exist_ok=True)
    written = 0
    for name, text in sorted(files.items()):
        p = os.path.join(out_dir, name)
        if (read_text(p) if os.path.isfile(p) else None) != text:
            with open(p, "w", encoding="utf-8", newline="") as f:
                f.write(text)
            if name.endswith(".py"):
                os.chmod(p, 0o755)
            written += 1
            print("compile: wrote " + p)
    print("compile --target codex: %d artifacts, %d written in %s" % (len(files), written, out_dir))
    return 0


def read_text(path):
    """Byte-exact read: no newline translation, so a CRLF artifact is stale."""
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def agents_on_disk(plugin_root):
    """[(agents/<f>.md, carries the generated marker)] for every agents/*.md."""
    d = os.path.join(plugin_root, "agents")
    if not os.path.isdir(d):
        return []
    found = []
    for f in sorted(os.listdir(d)):
        p = os.path.join(d, f)
        if f.endswith(".md") and os.path.isfile(p):
            found.append(("agents/" + f, GENERATED_MARK in read_text(p)))
    return found


# ------------------------------------------------------------------ main ----

def find_overlay():
    env = os.environ.get("APEX_DISPATCH_POLICY")
    if env:
        return env
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None
    p = os.path.join(top, ".claude", "apex-dispatch", "policy.json")
    return p if os.path.isfile(p) else None


def load_inputs(plugin_root):
    res = os.path.join(plugin_root, "resources")
    return {
        "default": load_json(os.path.join(res, "dispatch.default.json"), "default policy"),
        "sections": load_json(os.path.join(res, "sections.json"), "sections registry"),
        "schema": load_json(os.path.join(res, "schema.json"), "schema"),
    }


def merged_with_overlay(inputs, overlay_path):
    """The default policy merged with the overlay at overlay_path, disabled
    entries subtracted, validated with the schema, governance and overlay
    bounds (overlay_checks). Raises PolicyError naming every problem."""
    overlay = load_json(overlay_path, "overlay")
    secs = inputs["sections"]["sections"]
    try:
        merged = apply_disabled(merge_policy(inputs["default"], overlay, secs, overlay_path), secs, inputs["schema"])
        default_policy = apply_disabled(merge_policy(inputs["default"], {}, secs), secs, inputs["schema"])
        validate_policy(merged, inputs["schema"], "merged policy (overlay %s)" % overlay_path,
                        extra=lambda m: overlay_checks(default_policy, m))
    except (TypeError, KeyError, AttributeError) as e:
        # A value of the wrong shape (a list or object where an id, tag or flag
        # string belongs) that the named checks did not catch first: still a
        # named refusal, never a traceback.
        raise PolicyError(["overlay %s: a value has the wrong type for its field (%s: %s); ids, tags, classes, "
                           "roles and flags are strings" % (overlay_path, type(e).__name__, e)])
    return merged


def runtime_policy(plugin_root, overlay_path=None):
    """What runtime readers (route.sh, hooks) use: the committed
    resources/compiled/policy.json, or, when this repo has an overlay
    (overlay_path, else find_overlay()), the default merged with it through
    the same merge as --print-merged. Raises PolicyError."""
    if overlay_path is None:
        overlay_path = find_overlay()
    if overlay_path is None:
        return load_json(os.path.join(plugin_root, "resources", "compiled", "policy.json"), "compiled policy")
    return merged_with_overlay(load_inputs(plugin_root), overlay_path)


def main(argv):
    if not argv:
        print("usage: compile.py <plugin-root> [--check | --write | --print-merged] [--overlay PATH]", file=sys.stderr)
        return 2
    root, args = os.path.abspath(argv[0]), argv[1:]
    check = printing = write = False
    overlay_path = target = out_dir = None
    i = 0
    while i < len(args):
        a = args[i]
        if a in ("--target", "--out"):
            if i + 1 >= len(args):
                print("compile: %s needs a value" % a, file=sys.stderr)
                return 2
            if a == "--target":
                target = args[i + 1]
            else:
                out_dir = os.path.abspath(args[i + 1])
            i += 2
            continue
        if a == "--check":
            check = True
        elif a == "--print-merged":
            printing = True
        elif a == "--write":
            write = True
        elif a == "--overlay":
            if i + 1 >= len(args):
                print("compile: --overlay needs a path", file=sys.stderr)
                return 2
            overlay_path = args[i + 1]
            i += 1
        elif a in ("-h", "--help"):
            print(__doc__)
            return 0
        else:
            print("compile: unknown argument %s" % a, file=sys.stderr)
            return 2
        i += 1
    if sum((check, printing, write)) > 1:
        print("compile: --check, --write and --print-merged are exclusive", file=sys.stderr)
        return 2
    if target not in (None, "claude", "codex"):
        print("compile: --target must be codex (or claude, the default)", file=sys.stderr)
        return 2
    if out_dir is not None and target != "codex":
        print("compile: --out is only for --target codex", file=sys.stderr)
        return 2
    if target == "codex":
        if printing or overlay_path is not None:
            print("compile: --target codex takes only --out, --check and --write", file=sys.stderr)
            return 2
        try:
            return codex_target(root, load_inputs(root), out_dir, check)
        except PolicyError as e:
            for line in e.errors:
                print("compile: " + line, file=sys.stderr)
            return 1
    if overlay_path is not None and not (printing or write):
        check = True          # validating an overlay never rewrites the plugin unless --write says so
    try:
        inputs = load_inputs(root)
        artifacts = build(root, inputs)
        if overlay_path is None and printing:
            overlay_path = find_overlay()
        merged = None
        if overlay_path is not None:
            merged = merged_with_overlay(inputs, overlay_path)
    except PolicyError as e:
        for line in e.errors:
            print("compile: " + line, file=sys.stderr)
        return 1
    if printing:
        sys.stdout.write(dumps(merged if merged is not None else json.loads(artifacts["resources/compiled/policy.json"])))
        return 0
    expected = set(artifacts)
    on_disk = agents_on_disk(root)
    orphans = [a for a, marked in on_disk if marked and a not in expected]
    foreign = [a for a, marked in on_disk if not marked and a not in expected]
    if check:
        problems = []
        for rel in sorted(artifacts):
            p = os.path.join(root, rel)
            if not os.path.isfile(p):
                problems.append("missing: " + rel)
                continue
            if read_text(p) != artifacts[rel]:
                problems.append("stale: " + rel)
        problems += ["orphaned: " + a for a in orphans]
        problems += ["not generated: %s (agents/ is fully generated; remove it)" % a for a in foreign]
        for line in problems:
            print("compile --check: " + line, file=sys.stderr)
        if problems:
            print("compile --check: %d artifact(s) out of date; run scripts/compile.sh" % len(problems), file=sys.stderr)
            return 1
        print("compile --check: %d artifacts up to date%s" % (len(artifacts), "; overlay valid" if merged is not None else ""))
        return 0
    written = 0
    for rel, text in sorted(artifacts.items()):
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        cur = read_text(p) if os.path.isfile(p) else None
        if cur != text:
            with open(p, "w", encoding="utf-8", newline="") as f:
                f.write(text)
            written += 1
            print("compile: wrote " + rel)
    for a in orphans:
        os.remove(os.path.join(root, a))
        print("compile: removed " + a)
    print("compile: %d artifacts, %d written, %d removed%s" % (len(artifacts), written, len(orphans), "; overlay valid" if merged is not None else ""))
    for a in foreign:
        print("compile: %s is not a generated artifact; agents/ is fully generated, remove it" % a, file=sys.stderr)
    return 1 if foreign else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
