// SPDX-License-Identifier: MIT
// Generated by agent-harness-generator — MCP primitive (ADR-022).

import { appendFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { projectHarnessDir } from '../paths.js';
import { POLICY } from './policy.js';

/** One audit record per tool call. Append-only; never mutated. */
export interface AuditEntry {
  ts: string;
  tool: string;
  decision: 'allowed' | 'denied' | 'approval-required' | 'error';
  reason: string;
  durationMs?: number;
}

function logPath(): string {
  return process.env.HARNESS_AUDIT_LOG ?? join(projectHarnessDir(), 'audit.log');
}

export async function audit(entry: AuditEntry): Promise<void> {
  if (!POLICY.auditLog) return;
  const path = logPath();
  try {
    await mkdir(dirname(path), { recursive: true });
    await appendFile(path, JSON.stringify(entry) + '\n', 'utf-8');
  } catch {
    /* never let auditing crash a tool call */
  }
}
