// SPDX-License-Identifier: MIT
// Generated by agent-harness-generator — MCP primitive (ADR-022).

import { readHarnessJson } from '../paths.js';

export interface ToolCtx {
  /** Declared capabilities this tool needs. */
  needs: { network?: boolean; shell?: boolean; fileWrite?: boolean };
  /** Author/host has flagged this tool dangerous. */
  dangerous?: boolean;
}

export interface PolicyDecision {
  allowed: boolean;
  reason: string;
  requiresApproval: boolean;
}

export interface Policy {
  defaultDeny: boolean;
  allowNetwork: boolean;
  allowShell: boolean;
  allowFileWrite: boolean;
  requireApprovalForDangerous: boolean;
  toolTimeoutMs: number;
  maxToolCallsPerTurn: number;
  auditLog: boolean;
}

/** The safe floor, used when no policy file is found at all. */
export const DEFAULT_POLICY: Policy = {
  defaultDeny: true,
  allowNetwork: false,
  allowShell: false,
  allowFileWrite: false,
  requireApprovalForDangerous: true,
  toolTimeoutMs: 30000,
  maxToolCallsPerTurn: 8,
  auditLog: true,
};

/**
 * Loaded from the project's .harness/mcp-policy.json when present, else the
 * copy bundled with the package, else DEFAULT_POLICY. Read once at startup.
 */
export const POLICY: Policy = {
  ...DEFAULT_POLICY,
  ...readHarnessJson<Partial<Policy>>('mcp-policy.json', {}),
};

/**
 * The single gate every tool call passes through. Default-deny: a capability
 * the policy does not grant is refused, not silently allowed.
 */
export function decide(ctx: ToolCtx): PolicyDecision {
  if (ctx.needs.network && !POLICY.allowNetwork) {
    return { allowed: false, reason: 'network not permitted by policy', requiresApproval: false };
  }
  if (ctx.needs.shell && !POLICY.allowShell) {
    return { allowed: false, reason: 'shell not permitted by policy', requiresApproval: false };
  }
  if (ctx.needs.fileWrite && !POLICY.allowFileWrite) {
    return { allowed: false, reason: 'file-write not permitted by policy', requiresApproval: false };
  }
  const requiresApproval = !!ctx.dangerous && POLICY.requireApprovalForDangerous;
  return { allowed: true, reason: 'permitted', requiresApproval };
}

/** Wrap an async tool body with the policy's per-call timeout. */
export async function withTimeout<T>(fn: () => Promise<T>): Promise<T> {
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error('tool timed out')), POLICY.toolTimeoutMs);
  });
  try {
    return await Promise.race([fn(), timeout]);
  } finally {
    clearTimeout(timer!);
  }
}
