// SPDX-License-Identifier: MIT
// Generated by agent-harness-generator — MCP primitive (ADR-022).

export interface PromptDef {
  name: string;
  description: string;
  template: string;
}

/** Branded prompts apex-app-harness exposes as MCP prompts. */
export const PROMPTS: PromptDef[] = [
  {
    name: 'kickoff',
    description: 'Open a apex-app-harness session with the harness conventions in context.',
    template: 'You are operating apex-app-harness. Plan, implement, review, and test code changes\nUse the harness MCP tools; defer destructive actions to the user.',
  },
];
