// SPDX-License-Identifier: MIT
// Generated by agent-harness-generator — MCP primitive (ADR-022).

import { readFile } from 'node:fs/promises';
import { resolveHarnessFile } from '../paths.js';

export interface ResourceDef {
  uri: string;
  name: string;
  mimeType: string;
  read: () => Promise<string>;
}

async function readHarnessFile(name: string): Promise<string> {
  const path = resolveHarnessFile(name);
  if (!path) throw new Error(`harness file not found: .harness/${name} (run \`apex-app-harness init\`)`);
  return readFile(path, 'utf-8');
}

/** Read-only resources apex-app-harness exposes to hosts (docs, manifests, memory views). */
export const RESOURCES: ResourceDef[] = [
  {
    uri: 'harness://manifest',
    name: 'Harness manifest',
    mimeType: 'application/json',
    read: () => readHarnessFile('manifest.json'),
  },
  {
    uri: 'harness://capabilities',
    name: 'MCP capability manifest',
    mimeType: 'application/json',
    read: () => readHarnessFile('mcp-capabilities.json'),
  },
  {
    uri: 'harness://policy',
    name: 'MCP policy in force',
    mimeType: 'application/json',
    read: () => readHarnessFile('mcp-policy.json'),
  },
];
