// SPDX-License-Identifier: MIT
// Generated by agent-harness-generator — MCP primitive (ADR-022).

import type { ToolCtx } from './policy.js';
import { search as memorySearch, store as memoryStore } from '../memory.js';
import { route as routeTask } from '../route.js';
import { agents } from '../agents/index.js';

export interface ToolDef {
  name: string;
  description: string;
  /** JSON Schema for inputs — hosts inspect this to build their UI. */
  inputSchema: Record<string, unknown>;
  ctx: ToolCtx;
  run: (args: Record<string, unknown>) => Promise<unknown>;
}

function str(args: Record<string, unknown>, key: string): string {
  const v = args[key];
  if (typeof v !== 'string' || v.trim() === '') throw new Error(`\`${key}\` is required and must be a non-empty string`);
  return v;
}

/**
 * Deterministic tool registry for apex-app-harness. Tools that touch nothing
 * privileged declare an empty `needs`; privileged tools declare what they need
 * in `ctx` and are gated by the policy.
 */
export const TOOLS: ToolDef[] = [
  {
    name: 'ping',
    description: 'Health probe — returns the harness name and a timestamp. No privileged capability.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    ctx: { needs: {} },
    run: async () => ({ harness: 'apex-app-harness', ok: true, ts: new Date().toISOString() }),
  },
  {
    name: 'route',
    description:
      'Recommend a routing tier (barbarian/scholar/sage) for a task. Deterministic keyword + length heuristic, not a learned router — the signals behind each decision are returned with it.',
    inputSchema: {
      type: 'object',
      properties: { task: { type: 'string', description: 'The task to route.' } },
      required: ['task'],
      additionalProperties: false,
    },
    ctx: { needs: {} },
    run: async (args) => routeTask(str(args, 'task')),
  },
  {
    name: 'memory-search',
    description:
      'Search stored patterns. Lexical token-overlap ranking with recency decay over a local JSONL store — not embedding-based semantic search.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search text.' },
        limit: { type: 'integer', minimum: 1, maximum: 50, description: 'Max results (default 5).' },
      },
      required: ['query'],
      additionalProperties: false,
    },
    ctx: { needs: {} },
    run: async (args) => {
      const limit = typeof args.limit === 'number' ? args.limit : 5;
      return { results: await memorySearch(str(args, 'query'), limit) };
    },
  },
  {
    name: 'memory-store',
    description: 'Append a pattern to the harness memory store. Writes to .harness/memory.jsonl in the project.',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'The pattern to remember.' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Optional tags.' },
      },
      required: ['text'],
      additionalProperties: false,
    },
    ctx: { needs: { fileWrite: true } },
    run: async (args) => {
      const tags = Array.isArray(args.tags) ? args.tags.filter((t): t is string => typeof t === 'string') : [];
      return memoryStore(str(args, 'text'), tags);
    },
  },
  {
    name: 'agents',
    description: 'List the harness agents and their roles.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    ctx: { needs: {} },
    run: async () => ({ agents: agents.map((a) => ({ id: a.id, name: a.name, description: a.description })) }),
  },
];
