#!/usr/bin/env python3
# Generated by apex-dispatch scripts/compile.sh --target codex from resources/dispatch.default.json; edit the policy, not this file.
# A PreToolUse command hook: reads the tool call JSON on stdin (command as a string or an argv
# list); each simple command (split on ; & && || | and newlines, wrappers and package runners
# stripped, bash/sh/zsh -c scripts unwrapped) is checked; exit 2 with the reason on stderr
# denies, exit 0 allows. String matching, not a sandbox.
RULES = {
 "bypass_prefixes": [
  "--dangerously-",
  "--yolo",
  "--always-approve",
  "--full-auto"
 ],
 "bypass_substrings": [
  "danger-full-access"
 ],
 "deny_globs": [
  "* --dangerously-*",
  "* --yolo*",
  "* --always-approve*",
  "* --full-auto*",
  "git push --force*"
 ],
 "provider_forbidden_flags": {
  "aider": [
   "--yes-always",
   "--yes",
   "--auto-commits",
   "--dirty-commits",
   "--git",
   "--auto-lint",
   "--auto-test"
  ],
  "claude": [
   "--bare",
   "--dangerously-skip-permissions",
   "--allow-dangerously-skip-permissions"
  ],
  "codex": [
   "--dangerously-bypass-approvals-and-sandbox",
   "--approve-for-me",
   "danger-full-access",
   "-a"
  ],
  "grok": [
   "--dangerously-skip-permissions",
   "--yolo",
   "--always-approve",
   "--auto-approve",
   "--no-sandbox",
   "--worktree"
  ],
  "opencode": [
   "--dangerously-skip-permissions",
   "--yolo",
   "--auto",
   "--auto-approve"
  ]
 }
}

import fnmatch, json, os, re, shlex, sys

MAX_DEPTH = 4
WRAPPERS = {"env", "timeout", "sudo", "nice", "nohup", "stdbuf", "command", "exec", "time", "ionice", "doas"}
VALUED = {"sudo": {"-u", "-g", "-C", "-D", "-h", "-p", "-r", "-t", "-U"}, "timeout": {"-s", "--signal", "-k", "--kill-after"},
          "nice": {"-n"}, "ionice": {"-c", "-n"}, "env": {"-u", "--unset", "-C", "--chdir", "-S"},
          "stdbuf": {"-i", "-o", "-e"}, "doas": {"-u"}}
RUNNERS = {"npx", "bunx", "pnpx", "uvx"}
PACKAGES = {"opencode-ai": "opencode", "@openai/codex": "codex", "@anthropic-ai/claude-code": "claude",
            "aider-chat": "aider", "@vibe-kit/grok-cli": "grok"}
SHELLS = {"bash", "sh", "zsh", "dash", "ksh"}
ASSIGN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")


def split_segments(cmd):
    """Simple commands of a shell string: split on ; & && || | and newlines."""
    try:
        lex = shlex.shlex(cmd.replace("\n", " ; "), posix=True, punctuation_chars=";&|")
        lex.whitespace_split = True
        toks = list(lex)
    except ValueError:
        toks = cmd.replace("\n", " ; ").split()
    segs, seg = [], []
    for t in toks:
        if t and set(t) <= set(";&|"):
            if seg:
                segs.append(seg)
            seg = []
        else:
            seg.append(t)
    if seg:
        segs.append(seg)
    return segs


def package_bin(pkg):
    pkg = re.sub(r"(?<=.)@[^/@]*$", "", pkg)          # drop a version: opencode-ai@1.2 -> opencode-ai
    return PACKAGES.get(pkg, pkg.rsplit("/", 1)[-1])


def unwrap(words):
    """Strip env assignments, wrappers (env, timeout N, sudo, nice, nohup, stdbuf,
    command, exec, time) and package runners (npx/bunx/pnpx/uvx X, pnpm|yarn dlx X,
    pipx run X); returns the words of the command that actually runs."""
    w = list(words)
    while w:
        b = os.path.basename(w[0])
        if ASSIGN.match(w[0]):
            w = w[1:]
            continue
        if b in WRAPPERS:
            w = w[1:]
            while w and (w[0].startswith("-") or (b == "env" and ASSIGN.match(w[0]))):
                w = w[2:] if w[0] in VALUED.get(b, ()) else w[1:]
            if b == "timeout" and w:
                w = w[1:]                                 # the duration
            continue
        if b in RUNNERS or (b in ("pnpm", "yarn") and w[1:2] == ["dlx"]) or (b == "pipx" and w[1:2] == ["run"]):
            w = w[2:] if b in ("pnpm", "yarn", "pipx") else w[1:]
            while w and w[0].startswith("-"):
                w = w[2:] if w[0] in ("-p", "--package", "--from") else w[1:]
            if w:
                w = [package_bin(w[0])] + w[1:]
            return w
        break
    return w


def reason_words(words, depth):
    if depth > MAX_DEPTH or not words:
        return None
    for x in words:
        if x.startswith(tuple(RULES["bypass_prefixes"])) or any(s in x for s in RULES["bypass_substrings"]):
            return "bypass flag %s is forbidden" % x
    w = unwrap(words)
    if not w:
        return None
    line = " ".join(w)
    for g in RULES["deny_globs"]:
        if fnmatch.fnmatchcase(line, g):
            return "matches the deny rule Bash(%s)" % g
    base = os.path.basename(w[0])
    if base in SHELLS:
        for k, x in enumerate(w[1:], 1):
            if re.fullmatch(r"-[a-zA-Z]*c[a-zA-Z]*", x) and k + 1 < len(w):
                return reason_cmd(w[k + 1], depth + 1)
    for f in RULES["provider_forbidden_flags"].get(base, []):
        if any(a == f or a.startswith(f + "=") for a in w[1:]):
            return "flag %s is forbidden for %s" % (f, base)
    return None


def reason_cmd(cmd, depth=0):
    if depth > MAX_DEPTH:
        return None
    for g in RULES["deny_globs"]:
        if fnmatch.fnmatchcase(cmd, g):
            return "matches the deny rule Bash(%s)" % g
    for seg in split_segments(cmd):
        why = reason_words(seg, depth)
        if why:
            return why
    return None


def reason(cmd):
    if isinstance(cmd, list):                           # an argv list: one command, no shell parsing
        return reason_words([str(x) for x in cmd], 0)
    return reason_cmd(cmd)


def main():
    try:
        p = json.load(sys.stdin)
    except ValueError:
        return 0
    ti = p.get("tool_input") if isinstance(p, dict) else None
    cmd = ti.get("command") if isinstance(ti, dict) else None
    if not isinstance(cmd, (str, list)):
        return 0
    why = reason(cmd)
    if why:
        print("apex-dispatch: " + why, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
