#!/usr/bin/env python3
# Generated by apex-dispatch scripts/compile.sh --target codex from resources/dispatch.default.json; edit the policy, not this file.
# A PreToolUse command hook: reads the tool call JSON on stdin; exit 2 with the reason on
# stderr denies a shell command that breaks a rule, exit 0 allows it. Not a sandbox.
RULES = {
 "bypass_prefixes": [
  "--dangerously-",
  "--yolo",
  "--always-approve",
  "--full-auto"
 ],
 "bypass_substrings": [
  "danger-full-access"
 ],
 "deny_globs": [
  "* --dangerously-*",
  "* --yolo*",
  "* --always-approve*",
  "* --full-auto*",
  "git push --force*"
 ],
 "provider_forbidden_flags": {
  "aider": [
   "--yes-always",
   "--yes",
   "--auto-commits",
   "--dirty-commits",
   "--git",
   "--auto-lint",
   "--auto-test"
  ],
  "claude": [
   "--bare",
   "--dangerously-skip-permissions",
   "--allow-dangerously-skip-permissions"
  ],
  "codex": [
   "--dangerously-bypass-approvals-and-sandbox",
   "--approve-for-me",
   "danger-full-access",
   "-a"
  ],
  "grok": [
   "--dangerously-skip-permissions",
   "--yolo",
   "--always-approve",
   "--auto-approve",
   "--no-sandbox",
   "--worktree"
  ],
  "opencode": [
   "--dangerously-skip-permissions",
   "--yolo",
   "--auto",
   "--auto-approve"
  ]
 }
}

import fnmatch, json, os, re, shlex, sys


def words(cmd):
    try:
        lex = shlex.shlex(cmd, posix=True, punctuation_chars=";&|")
        lex.whitespace_split = True
        return list(lex)
    except ValueError:
        return cmd.split()


def reason(cmd):
    for g in RULES["deny_globs"]:
        if fnmatch.fnmatchcase(cmd, g):
            return "matches the deny rule Bash(%s)" % g
    seg = []
    for w in words(cmd) + [";"]:
        if w and set(w) <= set(";&|"):
            if seg:
                base = os.path.basename(seg[0])
                for f in RULES["provider_forbidden_flags"].get(base, []):
                    if any(a == f or a.startswith(f + "=") for a in seg[1:]):
                        return "flag %s is forbidden for %s" % (f, base)
            seg = []
            continue
        if w.startswith(tuple(RULES["bypass_prefixes"])) or any(s in w for s in RULES["bypass_substrings"]):
            return "bypass flag %s is forbidden" % w
        seg.append(w)
    return None


def main():
    try:
        p = json.load(sys.stdin)
    except ValueError:
        return 0
    ti = p.get("tool_input") if isinstance(p, dict) else None
    cmd = ti.get("command") if isinstance(ti, dict) else None
    if isinstance(cmd, list):
        cmd = " ".join(str(x) for x in cmd)
    if not isinstance(cmd, str):
        return 0
    why = reason(cmd)
    if why:
        print("apex-dispatch: " + why, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
